name: DEPLOY WALKOPS API

on:
  push:
    branches:
      - release-test
      - release-stage
      - release-prod
  
jobs:
  deploy-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        uses: allenevans/set-env@v2.0.0
        with:
          # SENTRY_ORG: sudofy
          # SENTRY_LOG_LEVEL: debug
          # SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          AWS_ACCESS_KEY_ID: AKIASZBTZPNX42D5IYOM
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          S3_BUCKET: elasticbeanstalk-us-east-1-833363181218
          APPLICATION_NAME: walkops
          # SUDOFY_SSS_API_TOKEN: ${{ secrets.SUDOFY_SSS_API_TOKEN }}

      # - name: Install Sentry CLI
      #   run: curl -sL https://sentry.io/get-cli/ | bash

      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Install Boto3
        run: pip install boto3==1.3.0

      - name: Install Nodejs
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Remove package-lock.json
        run: rm -f package-lock.json

      - name: Protected package.json
        run: mv package.json package.json.protected

      - name: Install npm packages
        run: npm i @actions/core axios git-last-commit string-template --no-optional

      - name: Install global npm packages
        run: npm i -g replace

      - name: Unprotected package.json
        run: mv package.json.protected package.json

      - name: Set custom environment variables
        run: node .github/scripts/setupEnv.js

      - name: Adding APM config files for core api
        run: node .github/scripts/setupAPMConfig.js
        env:
          ELK_APM_NAME: "walkops"    

      - name: Remove node modules
        run: rm -rf node_modules  

      - name: Remove git folder
        run: rm -rf .git

      - name: Generate deployment zip package
        run: zip -r /tmp/api.zip .

      # - name: Replace Sentry Release
      #   run: replace 'pw-unreleased-api' "$SENTRY_RELEASE" main.js

      # - name: create release in Sentry
      #   run: sentry-cli releases new -p pw-api $SENTRY_RELEASE

      # - name: Push commits to Sentry
      #   run: sentry-cli releases set-commits --auto $SENTRY_RELEASE

      - name: Push code on AWS Elasticbeanstalk
        run: python .github/scripts/beanstalk_api_deploy.py

      # - name: Deploy release to Sentry
      #   run: sentry-cli releases deploys $SENTRY_RELEASE new -e $SENTRY_ENVIRONMENT

      # - name: Deploy release to jira
      #   run: node .github/scripts/releaseVersionOnJira.js

      # - uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
      #   if: always() # Pick up events even if the job fails or is canceled.

  

